### ISSUE TITLE
 Print confirmation when book read status is changed #19 

### ISSUE THREAD

**Issue by chrismon88** [chrismon88/readinglist#4]
Print a confirmation message such as "You have read Automate the Boring Stuff by Al Sweigart" or "You have not read Harry Potter by JK Rowling".

**Comment by Hockeydan25** [comment]
@chrismon88  let's add a new line to so it reads better.

**Comment by chrismon88** [comment]
Thanks Dan for being a great partner on this project both tested this change and looks pretty!
